# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib {
  E:/Project_8Digit_BCD_teller/Project_8Digit_BCD_teller.srcs/sources_1/imports/new/Decoder.vhd
  E:/Project_8Digit_BCD_teller/Project_8Digit_BCD_teller.srcs/sources_1/new/Segment.vhd
}
read_xdc E:/Project_8Digit_BCD_teller/Project_8Digit_BCD_teller.srcs/constrs_1/imports/Downloads/Nexys4_Master.xdc
set_property used_in_implementation false [get_files E:/Project_8Digit_BCD_teller/Project_8Digit_BCD_teller.srcs/constrs_1/imports/Downloads/Nexys4_Master.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Project_8Digit_BCD_teller/Project_8Digit_BCD_teller.cache/wt [current_project]
set_property parent.project_dir E:/Project_8Digit_BCD_teller [current_project]
catch { write_hwdef -file Segment.hwdef }
synth_design -top Segment -part xc7a100tcsg324-1
write_checkpoint Segment.dcp
report_utilization -file Segment_utilization_synth.rpt -pb Segment_utilization_synth.pb
